[project]
name = "simple-job-applications-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flet[all]==0.28.3",
    "google-auth>=2.40.2",
    "gspread>=6.2.1",
]
